function Plot_muns(ax, np, stt, skip, factor)
    re = np.result;
    exp_mun = re.exp_mun;
    muns_mn = re.muns_mn;
    muns_log = re.muns_log;
    
    [muns_max, muns_max_pos] = max(muns_mn(:,2));

    semilogx(ax, exp_mun(stt:skip:end,1), exp_mun(stt:skip:end,2), 'ko', ...
        LineWidth = 2, ...
        MarkerSize = 15)
    ax.NextPlot = 'add';
    semilogx(ax, muns_log(:, 1), muns_log(:, 2), 'gs-', ...
        LineWidth = 2, ...
        DisplayName = 'ln(k_{n+1}^d/k_n^a\rho_{1,\infty})', ...
        MarkerSize = 15)
    semilogx(ax, muns_mn(:, 1), muns_mn(:, 2), 'k-', ...
        DisplayName = 'Equation (1)', ...
        LineWidth = 2)
    semilogx(ax, muns_mn(muns_max_pos, 1), muns_max, 'yp', ...
        MarkerFaceColor = 'y', ...
        LineWidth = 2, ...
        DisplayName = '\mu_{n^+}^s', ...
        MarkerSize = 15)
    x = 20:1e4;
    semilogx(x, factor*x.^(-1/3), 'k--', ...
        LineWidth = 2, ...
        DisplayName = '~n^{-1/3}')
    legend(Color = 'none', FontSize = 12)
    axis([20, 1e4, -0.5, 3])
end